/* Auto-generated by lua_embed_gen.lua -- DO NOT EDIT */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct lua_embed_entry {
    const char* name;
    const char* data;
    size_t      size;
} lua_embed_entry;

typedef struct lua_embed_bundle {
    const lua_embed_entry* data; /* NULL-terminated */
    const lua_embed_entry* main; /* NULL-terminated */
    const lua_embed_entry* preload; /* NULL-terminated */
} lua_embed_bundle;

extern const lua_embed_bundle lua_embed;

#ifdef __cplusplus
}
#endif
